---
layout: main
title: 'A BASHful Adventurer'
---

## A BASHFUL Adventurer

A troll through the backupdrive of fate has netted the missing files from afore.

This presentation is still best seen "live" but you can get a feel for it yourself on a Fedora box with all the proper dependancies installed.

* [Source](https://github.com/goozbach-presentation/A-BASHful-Adventurer.git)

