---
layout: main
title: 'A BASHful Adventurer'
---

## A BASHFUL Adventurer

This presentation is as it was presented at SELF2013, that is to say, kinda broken.
I discovered too late that much of the functionality was not in the git repo (An overzealous .gitignore). 
And I've not yet discovered which backup drive contains the original as presented at UTOSC2010.

At whatever future time I find time to dig through the backup drives to find the original sources you can be sure I'll post them here.

* [Source](https://github.com/goozbach-presentation/A-BASHful-Adventurer.git)

